"""
Report Generator Module.
Formats the agent's research output into a structured Markdown report.
"""

import os
from datetime import datetime


def generate_report(topic: str, content, output_dir: str = "sample_outputs") -> str:
    """
    Generate a structured Markdown report from the agent's research output.

    Args:
        topic: The research topic.
        content: The raw research content from the agent (str or list).
        output_dir: Directory to save the report.

    Returns:
        The file path of the generated report.
    """
    # Normalize content — Gemini 2.5 may return a list of content blocks
    if isinstance(content, list):
        text_parts = []
        for part in content:
            if isinstance(part, str):
                text_parts.append(part)
            elif isinstance(part, dict) and part.get("type") == "text":
                text_parts.append(part.get("text", ""))
            elif hasattr(part, "text"):
                text_parts.append(part.text)
        content = "\n".join(text_parts)
    content = str(content)
    # Create output directory if it doesn't exist
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(script_dir, output_dir)
    os.makedirs(output_path, exist_ok=True)

    # Generate filename from topic
    filename = topic.lower().replace(" ", "_").replace(":", "").replace("/", "_")
    # Truncate if too long
    filename = filename[:60] if len(filename) > 60 else filename
    filepath = os.path.join(output_path, f"{filename}.md")

    # Build the report
    report = _build_report(topic, content)

    # Write the report
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)

    return filepath


def _build_report(topic: str, content: str) -> str:
    """
    Build a formatted Markdown report with cover page and structured sections.
    """
    date_str = datetime.now().strftime("%B %d, %Y")

    # Cover page
    report_parts = [
        "---",
        "",
        f"# 📋 Research Report",
        "",
        f"## {topic}",
        "",
        "---",
        "",
        f"**Date:** {date_str}",
        "",
        "**Generated by:** Autonomous Research Agent (LangChain)",
        "",
        "**Tools Used:** Web Search (DuckDuckGo) | Knowledge Base (Wikipedia)",
        "",
        "---",
        "",
    ]

    # Check if the content already has structured sections
    has_sections = any(
        header in content
        for header in ["# Introduction", "## Introduction", "# Key Findings", "## Key Findings"]
    )

    if has_sections:
        # Content is already structured — use as-is
        report_parts.append(content)
    else:
        # Wrap raw content in a structured format
        report_parts.extend([
            "## Table of Contents",
            "",
            "1. [Introduction](#introduction)",
            "2. [Key Findings](#key-findings)",
            "3. [Challenges](#challenges)",
            "4. [Future Scope](#future-scope)",
            "5. [Conclusion](#conclusion)",
            "",
            "---",
            "",
            content,
        ])

    # Footer
    report_parts.extend([
        "",
        "---",
        "",
        "*This report was autonomously generated using LangChain with Google Gemini LLM,*",
        "*DuckDuckGo Web Search, and Wikipedia Knowledge Base.*",
    ])

    return "\n".join(report_parts)
